<?php

namespace Duf\MessagingBundle\Entity\Repository;

/**
* ConversationRepository
*
* This class was generated by the Doctrine ORM. Add your own custom
* repository methods below.
*/
class ConversationRepository extends \Doctrine\ORM\EntityRepository
{
	public function findByConversationsForUser($user, $options = null)
	{
		$qb = $this->_em->createQueryBuilder()
				   ->select('c')
				   ->from($this->_entityName, 'c')
				   ->leftJoin('DufMessagingBundle:ConversationUser', 'convUser', 'WITH', 'convUser.conversation = c.id')
				   ->leftJoin('DufMessagingBundle:Message', 'msg', 'WITH', 'msg.conversation = c.id')
				   ->where(':user = convUser.user')
				   ->setParameter('user', $user);

		if (isset($options['isDeleted']) && $options['isDeleted'] == true) {
			$qb->andWhere('convUser.isDeleted = 1');
		}
		else {
			$qb->andWhere('convUser.isDeleted != 1 OR convUser.isDeleted IS NULL');
		}

		if (isset($options['isAuthor']) && $options['isAuthor'] === true) {
			$qb->andWhere('msg.author = :author_id');
			$qb->setParameter('author_id', $user->getId());
		}

		$qb->orderBy('msg.created_at', 'DESC');

		return $qb->getQuery()->getResult();
	}
}
