<?php

namespace Duf\MessagingBundle\Entity\Repository;

/**
 * DraftRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DraftRepository extends \Doctrine\ORM\EntityRepository
{
	public function findByUserDrafts($user)
	{
		$qb = $this->_em->createQueryBuilder()
				   ->select('COUNT(draft)')
				   ->from($this->_entityName, 'draft')
				   ->where('draft.author = :user')
				   ->setParameter('user', $user);

		$result = $qb->getQuery()->getResult();

		if (isset($result[0][1])) {
			return (int)$result[0][1];
		}

		return 0;
	}
}
